### ISSUE TITLE
Final touch on Maintenance branch

### ISSUE THREAD

**Issue by raulvj** [raulvj/iso2-bank_A02#20]
@Aharon1377 , sorry to bother you but I have found a new error while running the site:site of the Maintenance branch project. Could you please check it?

Thanks.

**Comment by AaronRBG** [comment]
We revised the maintenance branch after the merges to ensure everything was as it was supposed to, and we make a few little changes. Here is the related commit: https://github.com/raulvj/iso2-bank_A02/commit/5fa3dda657ca44d6ac5811216a501ac091a4e5ed.

We want to explain that the bug in the CPD report listed as a duplication is not really one, but 2 very similar methods, and that the bug in the Checkstyle report listed as HideUtilityClassConstructor cannot be solved without destroying the project, or as least we do not know how to.
